services:
  app:
    build: .
    ports:
      - "13500:13500"
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=teste
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - mysql
      - ollama
    volumes:
        - ./src:/app/src
        - ./public:/app/public
        - ./sqlModel:/app/sqlModel
        - node_modules_volume:/app/node_modules

  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=teste
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=password
    depends_on:
      - mysql

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11435:11434" # Changed host port to 11435
    volumes:
     - ./sqlModel:/app/sqlModel
     - ollama_data:/root/.ollama
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
  ollama_data:
  node_modules_volume: